run:
	@python main.py

test:
	@python test.py

help:
	@echo	"Daily Coding"
	@echo
	@echo 	"Rand7"
	@echo
	@echo "run 		    To run the main.py file"
	@echo "test 		To run the test.py and validate the main.py functions"