run:
	@python Main.py

test:
	@python Test.py

help:
	@echo	"Daily Coding"
	@echo 
	@echo 	"Available target rules"
	@echo
	@echo "run 		To run the Main.py file"
	@echo "test 		To run the Test.py and validate the Main.py functions"